import { service }  from '../utils/axios';
import AuthService from '../modules/auth';
import ConversationService from '../modules/conversation';
import DocumentService from '../modules/document';
import DocumentLibraryService from '../modules/document-library';
import MembershipService from '../modules/membership';
import NotificationService from '../modules/notification';
import StudySetService from '../modules/study-set';
import TagService from '../modules/tag';
import TicketService from '../modules/ticket';
import UserService from '../modules/user';
import AdminUserApi from '../modules/admin-user';

export const authService = new AuthService({ api: service, model: 'auth' });
export const conversationService = new ConversationService({ api: service, model: 'conversation' });
export const documentService = new DocumentService({ api: service, model: 'document' });
export const documentLibraryService = new DocumentLibraryService({ api: service, model: 'document-library' });
export const membershipService = new MembershipService({ api: service, model: 'membership' });
export const notificationService = new NotificationService({ api: service, model: 'notification' });
export const tagService = new TagService({ api: service, model: 'tag' });
export const studySetService = new StudySetService({ api: service, model: 'study-set' });
export const ticketService = new TicketService({ api: service, model: 'ticket' });
export const userService = new UserService({ api: service, model: 'user' });
export const adminUserApi = new AdminUserApi({ api: service, model: '__unused__' });